### ISSUE TITLE
Menu selection does not work with Node 4 & Windows

### ISSUE THREAD

**Issue by SomeoneWeird** [workshopper/workshopper#120]
Menu renders but selection is not possible, have confirmed it only happens with node 4 on windows (I tested with 10, but have had reports of 7/8 breaking too)

See https://github.com/nodeschool/discussions/issues/1448

**Comment by martinheidegger** [comment]
I published a new version of workshopper-adventure, would you mind to try it?

**Comment by SomeoneWeird** [comment]
@martinheidegger This also affects other workshops like goingnative, so I'm pretty sure it's a bug in `workshopper`. I tried your latest change and it's still not working.

**Comment by martinheidegger** [comment]
Workshopper-adventure is a complete fork of workshopper! It doesn't have
much similarity anymore...

**Comment by kbwjosh** [comment]
@SomeoneWeird I agree. Ive tested nodejs vs4.0&4.1 it doesnt work on windows 8.1. 
Menu selection doesnt work.

**Comment by SomeoneWeird** [comment]
https://github.com/nodejs/node/issues/3006 is probably related.

**Comment by MexieAndCo** [comment]
Having the described problem, too.  Windows 8.1, Node 4.2.1.

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0

**Comment by martinheidegger** [comment]
Yes, it has been fixed in node 5.1.0 but there should be a message in the breaking node versions and a fallback to "non-tty" mode.

**Comment by martinheidegger** [comment]
In addition: Call for help: It would help a lot of if we had a package that returns "true" if interactive mode in node version is available. A interesting npm name could be `supports-cli-interation`:

```
require('supports-cli-interaction') // true or false
```

**Comment by jmbucknall** [comment]
Just a quick addendum: this is again broken in node 5.8.0 (Windows 10, fully updated). I can confirm it works in node 5.3.0 (happened to have it on another machine here, again Windows 10). I have reverted to 5.3.0 for now.

**Comment by benjamincarp** [comment]
this appears to also be an issue using the ubuntu for windows 10 bash and node v6.4.0

I also ran `node -p -e "Boolean(process.stdout.isTTY)"` and it returned true
